#!/usr/bin/env python3
"""
Hybrid: Use Camoufox browser context to call check_enter_email.do via JS.
bx-ua token auto-generated by baxia JS running in browser.
Then capture the response and continue flow.
"""
import time, random, string, json, re
from camoufox.sync_api import Camoufox

REGISTER_URL = "https://account.alibabacloud.com/register/intl_register.htm"

def find_frame(page):
    for f in page.frames[1:]:
        if "passport.alibabacloud.com" in f.url:
            return f
    return None

email = ''.join(random.choices(string.ascii_lowercase + string.digits, k=10)) + "@REDACTED"
pw = "Te!t9" + ''.join(random.choices(string.ascii_letters + string.digits, k=10))
print(f"Email: {email}")
print(f"Password: {pw}")

with Camoufox(headless=False, geoip=True, locale="en-US") as browser:
    page = browser.new_page()
    
    # Capture responses to check_enter_email.do
    api_responses = []
    def on_response(response):
        if "check_enter_email" in response.url:
            try:
                body = response.text()
            except:
                body = ""
            api_responses.append({
                "url": response.url[:150],
                "status": response.status,
                "body": body[:1000],
            })
            print(f"\n>>> API RESPONSE: {response.status} {response.url[:100]}")
            print(f"    Body: {body[:500]}")
    page.on("response", on_response)
    
    print("\n=== Loading page ===")
    page.goto(REGISTER_URL, timeout=120000, wait_until="domcontentloaded")
    page.wait_for_selector("iframe[src*='passport']", timeout=30000)
    time.sleep(5)
    
    frame = find_frame(page)
    
    # Step 2: Individual
    for _ in range(15):
        label = frame.query_selector("label:has-text('Individual')")
        if label and label.is_visible(): break
        time.sleep(2)
        frame = find_frame(page)
    label.click()
    time.sleep(2)
    frame.query_selector("a:has-text('Next')").click()
    time.sleep(5)
    
    # Step 3: Fill form via UI (this triggers baxia to generate bx-ua)
    frame = find_frame(page)
    frame.query_selector("#email").type(email, delay=30)
    frame.query_selector("#password").type(pw, delay=30)
    frame.query_selector("#confirmPwd").type(pw, delay=30)
    time.sleep(2)
    
    # Now try to call the API directly from within the frame context
    # baxia JS should be loaded and can generate bx-ua
    print("\n=== Trying JS fetch from frame context ===")
    
    # Method 1: Try to trigger the form's own submit handler
    result = frame.evaluate("""async () => {
        // Find the submit button and dispatch click
        const btn = document.querySelector('button.account__submit');
        if (!btn) return {error: 'no submit button'};
        
        // Check if baxia is loaded
        const hasBaxia = typeof window.baxia !== 'undefined' || typeof window._bx !== 'undefined';
        
        // Look for baxia-related globals
        const baxiaKeys = Object.keys(window).filter(k => k.includes('bx') || k.includes('baxia') || k.includes('nc'));
        
        return {
            hasBtn: true,
            btnText: btn.textContent,
            hasBaxia: hasBaxia,
            baxiaKeys: baxiaKeys.slice(0, 20),
            formData: {
                email: document.querySelector('#email')?.value,
                password: document.querySelector('#password')?.value,
            }
        };
    }""")
    print(f"Frame state: {json.dumps(result, indent=2)}")
    
    # Method 2: Try to submit the form directly
    print("\n=== Trying form.submit() ===")
    result2 = frame.evaluate("""async () => {
        const form = document.querySelector('form');
        if (!form) return {error: 'no form'};
        
        // Try to find and call any submit handler
        // Check for jQuery ajaxSubmit or similar
        const hasJQuery = typeof window.jQuery !== 'undefined';
        
        // Try native submit
        try {
            // Instead of form.submit() which navigates, let's try to 
            // use XMLHttpRequest like the original code does
            const email = document.querySelector('#email').value;
            const password = document.querySelector('#password').value;
            
            // Check if there's a baxia function that generates bx-ua
            let bxua = '';
            if (typeof window.baxia !== 'undefined' && typeof window.baxia.sign === 'function') {
                bxua = window.baxia.sign();
            }
            
            return {
                hasJQuery: hasJQuery,
                email: email,
                password: password ? '***' : '',
                bxua: bxua ? 'generated' : 'not generated',
                formAction: form.action,
                formMethod: form.method,
            };
        } catch(e) {
            return {error: e.toString()};
        }
    }""")
    print(f"Form info: {json.dumps(result2, indent=2)}")
    
    # Method 3: Just click the button and wait longer — maybe slider appears
    print("\n=== Clicking Sign Up and watching for slider ===")
    btns = frame.query_selector_all("button")
    for b in btns:
        if "sign up" in b.inner_text().lower():
            b.click()
            print("Clicked Sign Up")
            break
    
    # Watch for slider/captcha to appear
    for i in range(10):
        time.sleep(2)
        frame = find_frame(page)
        if not frame:
            print(f"[{i}] Frame lost!")
            break
        
        # Check for slider/captcha elements
        slider = frame.query_selector("#risk_slider_container .RiskSlider") or \
                  frame.query_selector("[class*='slider']") or \
                  frame.query_selector("#nc_1_n1z") or \
                  frame.query_selector(".nc_iconfont")
        
        # Check for any new visible elements
        vis_els = frame.query_selector_all("[class*='slider'], [class*='captcha'], [class*='verify'], [class*='punish'], [id*='nc_'], [class*='nc_']")
        found = []
        for el in vis_els:
            vis = el.is_visible()
            tag = el.evaluate("e => e.tagName")
            cls = el.get_attribute("class") or ""
            iid = el.get_attribute("id") or ""
            txt = ""
            try: txt = el.inner_text()[:60]
            except: pass
            found.append(f"<{tag}> id={iid} class={cls[:30]} vis={vis} text='{txt}'")
        
        # Check if slider became visible
        risk_slider = frame.query_selector("#risk_slider_container")
        risk_vis = risk_slider.is_visible() if risk_slider else False
        
        print(f"[{i}] risk_slider vis={risk_vis} | captcha elements: {len(found)}")
        for f in found[:5]:
            print(f"  {f}")
        
        # Check for nocaptcha iframe
        for cf in page.frames:
            if "nocaptcha" in cf.url or "captcha" in cf.url:
                print(f"  CAPTCHA FRAME: {cf.url[:100]}")
        
        if risk_vis:
            print("  >>> SLIDER APPEARED! <<<")
            page.screenshot(path="/home/ubuntu/alibaba-farm/slider_appeared.png")
            break
    
    # Final: check API responses
    print(f"\n=== API RESPONSES ({len(api_responses)}) ===")
    for r in api_responses:
        print(f"  {r['status']} {r['url']}")
        print(f"  Body: {r['body'][:300]}")
    
    page.screenshot(path="/home/ubuntu/alibaba-farm/final_state.png")
